### ISSUE TITLE
failed build on ubuntu 21.10

### ISSUE THREAD

**Issue by rafmeeusen** [google/pawn#7]
build error: 

/home/raf/repo/pawn/build/_deps/absl-src/absl/debugging/failure_signal_handler.cc:139:32: error: no matching function for call to ‘max(long int, int)’
  139 |   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;

**Comment by cblichmann** [comment]
398d8fcaa2dcfc1f69996de9a6c1083a9f7b7e01 fixes this for me when I try to build in a Docker container using the `ubuntu:21.10` image (after installing the required packages to build).
